site_name: DHIS2 Documentation
site_description: Official documentation of the DHIS 2 platform
site_author: DHIS2 Documentation Team
# site_url sets the canonical url - we want this to point to the latest version
site_url: 'https://docs.dhis2.org/en/'
copyright: 'Copyright &copy; 2008-2020 DHIS2 Team'
google_analytics: ['UA-157707339-2', 'docs.dhis2.org']
# edit_uri: ''
repo_url: https://github.com/dhis2/dhis2-docs
repo_name: 'dhis2-docs on GitHub'
# Query string example
# edit_uri: tree/master/src/commonmark/en/content/
use_directory_urls: false
# docs_dir:

extra:
    dhis2_version: 'master'
    dhis2_versions:
        - 'master'
        - '2.35'
        - '2.34'
        - '2.33'
        - '2.32'
        - '2.31'
        - '2.30'
        - '2.29'
    dhis2_language: 'en'
    dhis2_languages:
        en: 'English'
        fr: 'Français'
        es_419: 'Español (latinoamerica)'
        pt: 'Português'
        cs: 'Czech'
    social:
      - icon: fontawesome/brands/github
        link: https://www.github.com/dhis2
        name: DHIS2 source code on GitHub
      - icon: fontawesome/brands/docker
        link: https://hub.docker.com/repository/docker/dhis2
        name: DHIS2 on Docker
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/dhis_2
        name: DHIS2 on Twitter
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/dhis2
        name: DHIS2 on Facebook
      - icon: fontawesome/brands/discourse
        link: https://community.dhis2.org
        name: DHIS2 Community

theme:
    name: material
    logo: 'resources/images/logo.svg'
    favicon: 'resources/images/favicon.ico'
    features:
      - navigation.tabs
      - navigation.instant
      - toc.integration
    alternates:
      alt_marker: 'alt__'
    custom_dir: 'theme'
    palette:
      primary: 'black'
      accent: 'blue'
    language: 'en'

# our css
extra_css:
    - resources/css/mkdocs_dhis2.css

extra_javascript:
    - resources/javascript/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - edit_url
    - dhis2_docs
    - minify:
        minify_html: true

markdown_extensions:
    - codehilite:
        guess_lang: false
    - markdown_captions
    - toc:
        permalink: true
        toc_depth: 3
    - attr_list
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite:
        custom_inline:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true



# output when building
site_dir: ./target/en/


nav:
  - Use:
      Use: use/use.md
      User guide:
        alt__DHIS core version 2.35:
          What is DHIS2?: use/user-guide/dhis-core-version-235/what-is-dhis2.md
          Collecting data:
            - Data Entry: use/user-guide/dhis-core-version-235/collecting-data/data-entry.md
          Tracking individual level data:
            - Capture: use/user-guide/dhis-core-version-235/tracking-individual-level-data/capture.md
            - Event Capture: use/user-guide/dhis-core-version-235/tracking-individual-level-data/event-capture.md
            - Tracker Capture: use/user-guide/dhis-core-version-235/tracking-individual-level-data/tracker-capture.md
          Approving data:
            - Data Approval: use/user-guide/dhis-core-version-235/approving-data/data-approval.md
          Analysing data:
            - Reports: use/user-guide/dhis-core-version-235/analysing-data/reports.md
            - Data Visualizer: use/user-guide/dhis-core-version-235/analysing-data/data-visualizer.md
            - Pivot Tables: use/user-guide/dhis-core-version-235/analysing-data/pivot-tables.md
            - Maps: use/user-guide/dhis-core-version-235/analysing-data/maps.md
            - Dashboards: use/user-guide/dhis-core-version-235/analysing-data/dashboards.md
            - Event Reports: use/user-guide/dhis-core-version-235/analysing-data/event-reports.md
            - Event Visualizer: use/user-guide/dhis-core-version-235/analysing-data/event-visualizer.md
          Changing user settings:
            - Messaging: use/user-guide/dhis-core-version-235/changing-user-settings/messaging.md
            - User account preferences: use/user-guide/dhis-core-version-235/changing-user-settings/user-account-preferences.md
          Configuring the system:
            - Metadata: use/user-guide/dhis-core-version-235/configuring-the-system/metadata.md
            - Users, Roles and Groups: use/user-guide/dhis-core-version-235/configuring-the-system/users-roles-and-groups.md
            - User authorities: use/user-guide/dhis-core-version-235/configuring-the-system/user-authorities.md
            - About sharing of objects: use/user-guide/dhis-core-version-235/configuring-the-system/about-sharing-of-objects.md
            - Maps: use/user-guide/dhis-core-version-235/configuring-the-system/maps.md
            - Report: use/user-guide/dhis-core-version-235/configuring-the-system/report.md
            - System settings: use/user-guide/dhis-core-version-235/configuring-the-system/system-settings.md
          Maintaining the system:
            - Data Administration: use/user-guide/dhis-core-version-235/maintaining-the-system/data-administration.md
            - Visualize usage statistics: use/user-guide/dhis-core-version-235/maintaining-the-system/visualize-usage-statistics.md
            - Datastore Manager: use/user-guide/dhis-core-version-235/maintaining-the-system/datastore-manager.md
            - Scheduling: use/user-guide/dhis-core-version-235/maintaining-the-system/scheduling.md
            - Import/Export App: use/user-guide/dhis-core-version-235/maintaining-the-system/importexport-app.md
            - Metadata synchronizing: use/user-guide/dhis-core-version-235/maintaining-the-system/metadata-synchronizing.md
          Understanding the data model:
            - About data dimensions: use/user-guide/dhis-core-version-235/understanding-the-data-model/about-data-dimensions.md
            - Additional data dimensions: use/user-guide/dhis-core-version-235/understanding-the-data-model/additional-data-dimensions.md
            - Relationship model: use/user-guide/dhis-core-version-235/understanding-the-data-model/relationship-model.md
          Additional information:
            - DHIS2 Glossary: use/user-guide/dhis-core-version-235/additional-information/dhis2-glossary.md
            - Demo server, live package and database design: use/user-guide/dhis-core-version-235/additional-information/demo-server-live-package-and-database-design.md
            - DHIS2 Tutorials: use/user-guide/dhis-core-version-235/additional-information/dhis2-tutorials.md
            - DHIS2 Frequently Asked Questions: use/user-guide/dhis-core-version-235/additional-information/dhis2-frequently-asked-questions.md
            - Release and upgrade notes: use/user-guide/dhis-core-version-235/additional-information/release-and-upgrade-notes.md
        alt__DHIS core version 2.34:
          - Getting started - help to navigate the user guide: use/user-guide/dhis-core-version-234/getting-started-help-to-navigate-the-user-guide.md
          - What is DHIS2?: use/user-guide/dhis-core-version-234/what-is-dhis2.md
          - Managing dashboards: use/user-guide/dhis-core-version-234/managing-dashboards.md
          - Messaging: use/user-guide/dhis-core-version-234/messaging.md
          - Using the Data Entry app: use/user-guide/dhis-core-version-234/using-the-data-entry-app.md
          - Using the Event Capture app: use/user-guide/dhis-core-version-234/using-the-event-capture-app.md
          - Using the Tracker Capture app: use/user-guide/dhis-core-version-234/using-the-tracker-capture-app.md
          - Using the Capture app: use/user-guide/dhis-core-version-234/using-the-capture-app.md
      Optional Apps:
        Action Tracker App:
          alt__App version 1.0:
            - 'About this guide': use/optional-apps/action-tracker-app/app-version-10/about-this-guide.md
            - Dashboard and Demo Server: use/optional-apps/action-tracker-app/app-version-10/dashboard-and-demo-server.md
            - Planning, tracking and analyzing actions: use/optional-apps/action-tracker-app/app-version-10/planning-tracking-and-analyzing-actions.md
            - Maintenance and Support: use/optional-apps/action-tracker-app/app-version-10/maintenance-and-support.md
        Bottleneck Analysis App:
          alt__App version 1.2.2:
            - 'About this guide': use/optional-apps/bottleneck-analysis-app/app-version-122/about-this-guide.md
            - Introduction and Usage: use/optional-apps/bottleneck-analysis-app/app-version-122/introduction-and-usage.md
            - Installation and Configuration: use/optional-apps/bottleneck-analysis-app/app-version-122/installation-and-configuration.md
            - User Implementation: use/optional-apps/bottleneck-analysis-app/app-version-122/user-implementation.md
        Interactive Scorecard App:
          alt__App version 0.1:
            - 'About this guide': use/optional-apps/interactive-scorecard-app/app-version-01/about-this-guide.md
            - Introduction and Usage: use/optional-apps/interactive-scorecard-app/app-version-01/introduction-and-usage.md
        WHO Data Quality Tool:
          - Installation and configuration: use/optional-apps/who-data-quality-tool/installation-and-configuration.md
          - Usage and interpretation: use/optional-apps/who-data-quality-tool/usage-and-interpretation.md
  - Implement:
      Implement: implement/implement.md
      Implementer guide:
        - A quick guide to DHIS2 implementation: implement/implementer-guide/a-quick-guide-to-dhis2-implementation.md
        - Conceptual Design Principles: implement/implementer-guide/conceptual-design-principles.md
        - DHIS 2 Documentation Guide: implement/implementer-guide/dhis-2-documentation-guide.md
      Tracker Implementation guide:
        - 'Target audience': implement/tracker-implementation-guide/target-audience.md
        - 'Introduction': implement/tracker-implementation-guide/introduction.md
      Software Release Information:
        DHIS 2 core releases:
          alt__DHIS core version 2.35:
            - Release Notes: implement/software-release-information/dhis-2-core-releases/dhis-core-version-235/release-notes.md
            - Upgrade Notes: implement/software-release-information/dhis-2-core-releases/dhis-core-version-235/upgrade-notes.md
          alt__DHIS core version 2.34:
            - Release Notes: implement/software-release-information/dhis-2-core-releases/dhis-core-version-234/release-notes.md
            - Upgrade Notes: implement/software-release-information/dhis-2-core-releases/dhis-core-version-234/upgrade-notes.md
          alt__DHIS core version 2.33:
            - Release Notes: implement/software-release-information/dhis-2-core-releases/dhis-core-version-233/release-notes.md
            - Upgrade Notes: implement/software-release-information/dhis-2-core-releases/dhis-core-version-233/upgrade-notes.md
        Android app releases:
          alt__DHIS core version 2.35:
            alt__Android app version 2.3.0:
              - Release Notes: implement/software-release-information/android-app-releases/dhis-core-version-235/android-app-version-230/release-notes.md
          alt__DHIS core version 2.34:
            alt__Android app version 2.2.0:
              - Release Notes: implement/software-release-information/android-app-releases/dhis-core-version-234/android-app-version-220/release-notes.md
            alt__Android app version 2.1.0:
              - Release Notes: implement/software-release-information/android-app-releases/dhis-core-version-234/android-app-version-210/release-notes.md
  - Develop:
      Develop: develop/develop.md
      DHIS 2 Developer guide:
        alt__DHIS core version 2.35:
          - Apps: develop/dhis-2-developer-guide/dhis-core-version-235/apps.md
          - Development Infrastructure: develop/dhis-2-developer-guide/dhis-core-version-235/development-infrastructure.md
          - DHIS2 and R integration: develop/dhis-2-developer-guide/dhis-core-version-235/dhis2-and-r-integration.md
        alt__DHIS core version 2.34:
          - Apps: develop/dhis-2-developer-guide/dhis-core-version-234/apps.md
          - Development Infrastructure: develop/dhis-2-developer-guide/dhis-core-version-234/development-infrastructure.md
          - DHIS2 and R integration: develop/dhis-2-developer-guide/dhis-core-version-234/dhis2-and-r-integration.md
      DHIS 2 API Javadocs: https://docs.dhis2.org/master/javadoc/
      DHIS 2 Android SDK Developer Guide:
        - 'About this guide': develop/dhis-2-android-sdk-developer-guide/about-this-guide.md
        - 'Compatibility: SDK / core / Android': develop/dhis-2-android-sdk-developer-guide/compatibility-sdk-core-android.md
        - 'Overview': develop/dhis-2-android-sdk-developer-guide/overview.md
  - Manage:
      Manage: manage/manage.md
      DHIS 2 System Administration guide:
        alt__DHIS core version 2.35:
          - Installation: manage/dhis-2-system-administration-guide/dhis-core-version-235/installation.md
          - Monitoring: manage/dhis-2-system-administration-guide/dhis-core-version-235/monitoring.md
          - Audit: manage/dhis-2-system-administration-guide/dhis-core-version-235/audit.md
          - Using Gateways for SMS reporting: manage/dhis-2-system-administration-guide/dhis-core-version-235/using-gateways-for-sms-reporting.md
        alt__DHIS core version 2.34:
          - Installation: manage/dhis-2-system-administration-guide/dhis-core-version-234/installation.md
          - Monitoring: manage/dhis-2-system-administration-guide/dhis-core-version-234/monitoring.md
          - Audit: manage/dhis-2-system-administration-guide/dhis-core-version-234/audit.md
          - Using Gateways for SMS reporting: manage/dhis-2-system-administration-guide/dhis-core-version-234/using-gateways-for-sms-reporting.md
        alt__DHIS core version 2.33:
          - Installation: manage/dhis-2-system-administration-guide/dhis-core-version-233/installation.md
          - Using Gateways for SMS reporting: manage/dhis-2-system-administration-guide/dhis-core-version-233/using-gateways-for-sms-reporting.md
        alt__DHIS core version master:
          - Installation: manage/dhis-2-system-administration-guide/dhis-core-version-master/installation.md
          - Monitoring: manage/dhis-2-system-administration-guide/dhis-core-version-master/monitoring.md
          - Audit: manage/dhis-2-system-administration-guide/dhis-core-version-master/audit.md
          - Using Gateways for SMS reporting: manage/dhis-2-system-administration-guide/dhis-core-version-master/using-gateways-for-sms-reporting.md
  - Topics:
    - alt__Metadata:
        DHIS 2 WHO Digital Health Data Toolkit:
          - About the WHO Digital Health Data Toolkit: topics/metadata/dhis-2-who-digital-health-data-toolkit/about-the-who-digital-health-data-toolkit.md
          - General design principles for WHO metadata packages: topics/metadata/dhis-2-who-digital-health-data-toolkit/general-design-principles-for-who-metadata-packages.md
          - Naming conventions: topics/metadata/dhis-2-who-digital-health-data-toolkit/naming-conventions.md
    - alt__User Stories:
        - Improving surveillance of Visceral Leishmaniasis VL in Somalia: topics/user-stories/improving-surveillance-of-visceral-leishmaniasis-vl-in-somalia.md
        - DHIS2 in the Autonomous Region of Kurdistan, Iraq: topics/user-stories/dhis2-in-the-autonomous-region-of-kurdistan-iraq.md
